title: Панель управления
href: index.yaml
items:
- name: Обзор
  href: mini-apps/settings/overview.md
- name: Настройки
  items:
    - name: Информация
      href: mini-apps/settings/general/information.md
    - name: Размещение
      href: mini-apps/settings/general/placement.md
    - name: Оформление
      href: mini-apps/settings/general/design.md
    - name: Отображение
      href: mini-apps/settings/general/display.md
    - name: Правовые документы
      href: mini-apps/settings/general/legal-docs.md
    - name: Другие платформы
      href: mini-apps/settings/general/other-platforms.md
    - name: Дополнительные
      href: mini-apps/settings/general/additional.md
- name: Разработка
  items:
    - name: Ключи доступа
      href: mini-apps/settings/development/keys.md
    - name: Хранимые процедуры
      href: mini-apps/settings/development/stored-procedures.md
- name: Модерация
  href: mini-apps/settings/moderation.md
- name: Монетизация
  href: mini-apps/settings/monetization.md
- name: Платежи
  items:
    - name: Подключение
      href: mini-apps/settings/payments/setting-up.md
    - name: Транзакции
      href: mini-apps/settings/payments/transactions.md
    - name: Вывод
      href: mini-apps/settings/payments/withdrawal.md
- name: Статистика
  items:
    - name: Аудитория
      href: mini-apps/settings/stats/audience.md
    - name: Платежи
      href: mini-apps/settings/stats/payments.md
    - name: Запросы к API
      href: mini-apps/settings/stats/api-requests.md
    - name: Рекламная монетизация
      href: mini-apps/settings/stats/monetization.md
    - name: Оптимизация
      href: mini-apps/settings/stats/optimization.md
- name: Соц. механики
  items:
    - name: Уведомления
      href: mini-apps/settings/social-mechanics/notifications.md
- name: События приложения
  href: mini-apps/settings/history.md
- name: Администраторы
  href: mini-apps/settings/managers.md
- name: Доступ к приложению
  href: mini-apps/settings/access-to-app.md
- name: Тестовые группы
  href: mini-apps/settings/test-groups.md
- name: Помощь
  href: mini-apps/settings/help.md
- name: Где используются настройки в интерфейсе ВКонтакте
  href: mini-apps/settings/design-examples.md